class BusinessInfo(object) :
    name = ""
    address = ""
    city = ""
    province = ""
    latitude = 0.0
    longitude = 0.0
    website = ""
    emailAddress = ""
    phoneNumber = ""
    classification = ""
    benefit = ""
    imageUrl = ""
    memberSince = "" 